{
 "cells": [
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "# Simple model\n",
    "\n",
    "This is the code to train a simple model using keras. This seems to be unefficient, making a very complex and big CNN. However with no no more then 3500 images it converges well to almost 100% accuracy (on evaluation). Still only using, one model per person. Using only one type of attack.\n",
    "\n",
    "The need of a more robust method would be good. A model that can generilize from multiple people and corectly discriminate live faces from spoofed ones, form different attacks. That would require more and better models of style tranfer."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 1,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "('64bit', 'WindowsPE')\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Using TensorFlow backend.\n"
     ]
    }
   ],
   "source": [
    "import tensorflow as tf\n",
    "from tensorflow.keras import layers\n",
    "from tensorflow.keras.models import Sequential\n",
    "from keras import callbacks\n",
    "from keras.regularizers import l2\n",
    "import pickle\n",
    "import numpy as np\n",
    "import datetime\n",
    "import os\n",
    "import random\n",
    "now_datetime  = datetime.datetime.now()\n",
    "NAME = f\"#Face_spoofing300x2_{now_datetime.day:02d}{now_datetime.month:02d}{now_datetime.year}_{now_datetime.hour:02d}{now_datetime.minute:02d}\"\n",
    "dir_pickle = \"database_serialized\"\n",
    "dir_models_save = \"models\"\n",
    "ignore = []\n",
    "import platform\n",
    "print(platform.architecture())"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Model format\n",
    "This is a simple CNN, that is made of a convolutional and a dense layer. below you choose the numbers of filters of each concolutional layer, and the numbers of neurons of each dense layer"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 2,
   "metadata": {},
   "outputs": [],
   "source": [
    "'''\n",
    "format1 = [[80,140,320],[80,140,320]]\n",
    "format2 = [[400,300,200],[400,300,200]]\n",
    "'''\n",
    "format3 = [[80,120,300],[400]]\n",
    "NN_formats = [format3]\n",
    "\n"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## The model\n",
    "The model creaeted here is enought for an almost ideal (acc = 98%) spoof detection model, as expected from a liveness detection methods that include deep learning as shown on many [studies](https://www.emerald.com/insight/content/doi/10.1108/SR-08-2015-0136/full/html) before.\n",
    "\n",
    "However the artifical creation of spoofed images, may reduce its performance. For 2 different reasons:\n",
    "1. Non perfect spoofed images. The creating of a model that can generate an spoofed image relayes much on the single image and the trainning data used to create such model. If both are not manage correctly, the creation of bad models may occur. Not to mention that some types of attacks are really hard to imitate e.g. print attacks.\n",
    "2. Reduced numbers of data. There isn't much data online for this type of problem, and it to the creation of individuals models for each person may prove unresenable, for each person must have minutes (about two) of video of their faces, for a better conversion of the CNN.\n",
    "\n",
    "For those reasons, it would be needed a deep leraning method that requires less data, to generalize. Something that could be accuired by [this](https://www.sciencedirect.com/science/article/pii/S1047320318301044) method."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "metadata": {},
   "outputs": [],
   "source": [
    "def load_data(person):   \n",
    "    pickle_path =os.path.join(dir_pickle,person)\n",
    "    pickle_in = open(os.path.join(pickle_path,f\"X{person}.pickle\"),\"rb\")\n",
    "    X = pickle.load(pickle_in)\n",
    "    pickle_in.close()\n",
    "    pickle_in = open(os.path.join(pickle_path,f\"y{person}.pickle\"),\"rb\")\n",
    "    y = pickle.load(pickle_in)\n",
    "    pickle_in.close()\n",
    "    \n",
    "    X = X.astype(np.float16)/255.0\n",
    "    \n",
    "    return X, y\n",
    "\n",
    "def create_model(person, pickle_path,format_convolution,format_dense):\n",
    "    model = Sequential()\n",
    "    is_first = True\n",
    "    # Convolutional layers\n",
    "    for format_c in format_convolution:\n",
    "        if is_first:\n",
    "            model.add(layers.Conv2D(format_c,(3,3),input_shape=X.shape[1:]))\n",
    "            is_first = False\n",
    "        else:\n",
    "            model.add(layers.Conv2D(format_c,(3,3)))\n",
    "        model.add(layers.Activation(\"relu\"))\n",
    "        model.add(layers.MaxPool2D(pool_size=(3,3)))\n",
    "    #Flatten the model if needed\n",
    "    model.add(layers.Flatten())\n",
    "    \n",
    "    #Dense layers\n",
    "    for format_d in format_dense:\n",
    "        model.add(layers.Dropout(0.12))\n",
    "        model.add(layers.Dense(format_d,activation=\"relu\",kernel_regularizer=l2(0.002)))\n",
    "    \n",
    "    #Output layer\n",
    "    model.add(layers.Dense(1,activation=\"sigmoid\"))\n",
    "    \n",
    "    \n",
    "    model.compile(loss=\"binary_crossentropy\",\n",
    "              optimizer = \"adam\",\n",
    "              metrics= [\"accuracy\"])\n",
    "    \n",
    "    return model"
   ]
  },
  {
   "cell_type": "markdown",
   "metadata": {},
   "source": [
    "## Trainning your model\n",
    "This line trains your model. It is recoomend to use tensorflow-gpu, and to be carefull if your gpu can handle the data, if  you are having *ResourceExhaustedError*, try reducing the **batch size**, or the sizes of your **tesors**.\n",
    "\n",
    "Keep the eye on your **validation** because that shows your live performance without trainning bias. You may use checkpoints to get the best validation accuracy."
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 4,
   "metadata": {},
   "outputs": [],
   "source": [
    "def create_callbacks(person,format_convolution,format_dense):\n",
    "    if not os.path.isdir(os.path.join(dir_models_save,person)):\n",
    "        os.mkdir(os.path.join(dir_models_save,person))\n",
    "    checkpoints = callbacks.ModelCheckpoint(filepath=os.path.join(dir_models_save,person,f\"{person}{NAME}{format_convolution}{format_dense}.h5\"),\n",
    "                                                monitor=\"val_acc\",\n",
    "                                                mode = \"max\",\n",
    "                                                verbose = 1,\n",
    "                                                save_weights_only=False,\n",
    "                                                save_best_only=True)\n",
    "    return checkpoints\n",
    "        \n",
    "def create_validation(person,val_test_split=0.25):\n",
    "    ValSet = []\n",
    "    pickle_path =os.path.join(dir_pickle,person)\n",
    "    pickle_in = open(os.path.join(pickle_path,f\"X{person}Test.pickle\"),\"rb\")\n",
    "    Xval = pickle.load(pickle_in)\n",
    "    pickle_in.close()\n",
    "    pickle_in = open(os.path.join(pickle_path,f\"y{person}Test.pickle\"),\"rb\")\n",
    "    yval = pickle.load(pickle_in)\n",
    "    pickle_in.close()\n",
    "    Xval = Xval.astype(np.float16)\n",
    "    Xval = Xval/255.0\n",
    "    yval = yval\n",
    "    print(f\"1{Xval.shape}\")\n",
    "    n_exs = int(len(Xval[0]) * val_test_split)\n",
    "    ValSet = [np.array(Xval[:n_exs-1]),yval[:n_exs-1]]\n",
    "    print(f\"2{ValSet[0].shape}\")\n",
    "    return ValSet\n",
    "    \n",
    "    "
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 5,
   "metadata": {},
   "outputs": [],
   "source": [
    "from keras.backend.tensorflow_backend import set_session\n",
    "from keras.backend.tensorflow_backend import clear_session\n",
    "from keras.backend.tensorflow_backend import get_session\n",
    "import tensorflow\n",
    "import gc\n",
    "# Reset Keras Session\n",
    "def reset_keras():\n",
    "    sess = get_session()\n",
    "    clear_session()\n",
    "    sess.close()\n",
    "    sess = get_session()\n",
    "\n",
    "    try:\n",
    "        del classifier # this is from global space - change this as you need\n",
    "    except:\n",
    "        pass\n",
    "\n",
    "    print(gc.collect()) # if it's done something you should see a number being outputted\n",
    "\n",
    "    # use the same config as you used to create the session\n",
    "    config = tensorflow.ConfigProto()\n",
    "    config.gpu_options.per_process_gpu_memory_fraction = 1\n",
    "    config.gpu_options.visible_device_list = \"0\"\n",
    "    set_session(tensorflow.Session(config=config))"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 6,
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 001 data\n",
      "1(1153, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "WARNING:tensorflow:From E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\ops\\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Call initializer instance with the dtype argument instead of passing it to the constructor\n",
      "WARNING:tensorflow:From E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\ops\\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.\n",
      "Instructions for updating:\n",
      "Use tf.where in 2.0, which has the same broadcast rule as np.where\n",
      "Start 001 trainning\n",
      "Train on 10635 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "10630/10635 [============================>.] - ETA: 0s - loss: 0.1541 - acc: 0.9789\n",
      "Epoch 00001: val_acc improved from -inf to 0.79730, saving model to models\\001\\001#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "10635/10635 [==============================] - 160s 15ms/sample - loss: 0.1541 - acc: 0.9789 - val_loss: 5.6104 - val_acc: 0.7973\n",
      "Epoch 2/4\n",
      "10630/10635 [============================>.] - ETA: 0s - loss: 0.0957 - acc: 0.9971\n",
      "Epoch 00002: val_acc improved from 0.79730 to 1.00000, saving model to models\\001\\001#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "10635/10635 [==============================] - 147s 14ms/sample - loss: 0.0957 - acc: 0.9971 - val_loss: 0.0329 - val_acc: 1.0000\n",
      "Epoch 3/4\n",
      "10630/10635 [============================>.] - ETA: 0s - loss: 0.0275 - acc: 0.9980\n",
      "Epoch 00003: val_acc did not improve from 1.00000\n",
      "10635/10635 [==============================] - 144s 14ms/sample - loss: 0.0276 - acc: 0.9980 - val_loss: 0.2261 - val_acc: 1.0000\n",
      "Epoch 4/4\n",
      "10630/10635 [============================>.] - ETA: 0s - loss: 0.0766 - acc: 0.9992\n",
      "Epoch 00004: val_acc did not improve from 1.00000\n",
      "10635/10635 [==============================] - 144s 14ms/sample - loss: 0.0765 - acc: 0.9992 - val_loss: 0.0511 - val_acc: 0.9730\n",
      "44\n",
      "Loading 002 data\n",
      "1(1136, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 002 trainning\n",
      "Train on 2830 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2820/2830 [============================>.] - ETA: 0s - loss: 0.1986 - acc: 0.9858\n",
      "Epoch 00001: val_acc improved from -inf to 0.71622, saving model to models\\002\\002#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2830/2830 [==============================] - 41s 14ms/sample - loss: 0.1979 - acc: 0.9859 - val_loss: 1.4984 - val_acc: 0.7162\n",
      "Epoch 2/4\n",
      "2820/2830 [============================>.] - ETA: 0s - loss: 0.1952 - acc: 0.9879\n",
      "Epoch 00002: val_acc improved from 0.71622 to 0.72973, saving model to models\\002\\002#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2830/2830 [==============================] - 40s 14ms/sample - loss: 0.1947 - acc: 0.9880 - val_loss: 6.4938 - val_acc: 0.7297\n",
      "Epoch 3/4\n",
      "2820/2830 [============================>.] - ETA: 0s - loss: 0.0230 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 0.72973\n",
      "2830/2830 [==============================] - 39s 14ms/sample - loss: 0.0229 - acc: 1.0000 - val_loss: 2.7523 - val_acc: 0.7027\n",
      "Epoch 4/4\n",
      "2820/2830 [============================>.] - ETA: 0s - loss: 0.1059 - acc: 0.9989\n",
      "Epoch 00004: val_acc improved from 0.72973 to 0.95946, saving model to models\\002\\002#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2830/2830 [==============================] - 40s 14ms/sample - loss: 0.1058 - acc: 0.9989 - val_loss: 0.3577 - val_acc: 0.9595\n",
      "49572\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 004 data\n",
      "1(990, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 004 trainning\n",
      "Train on 2544 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2540/2544 [============================>.] - ETA: 0s - loss: 0.2904 - acc: 0.9646\n",
      "Epoch 00001: val_acc improved from -inf to 0.82432, saving model to models\\004\\004#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2544/2544 [==============================] - 37s 14ms/sample - loss: 0.2900 - acc: 0.9646 - val_loss: 1.7364 - val_acc: 0.8243\n",
      "Epoch 2/4\n",
      "2540/2544 [============================>.] - ETA: 0s - loss: 0.0376 - acc: 1.0000\n",
      "Epoch 00002: val_acc improved from 0.82432 to 0.85135, saving model to models\\004\\004#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2544/2544 [==============================] - 36s 14ms/sample - loss: 0.0376 - acc: 1.0000 - val_loss: 1.4647 - val_acc: 0.8514\n",
      "Epoch 3/4\n",
      "2540/2544 [============================>.] - ETA: 0s - loss: 0.1119 - acc: 0.9929\n",
      "Epoch 00003: val_acc improved from 0.85135 to 0.90541, saving model to models\\004\\004#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2544/2544 [==============================] - 36s 14ms/sample - loss: 0.1119 - acc: 0.9929 - val_loss: 0.9901 - val_acc: 0.9054\n",
      "Epoch 4/4\n",
      "2540/2544 [============================>.] - ETA: 0s - loss: 0.0522 - acc: 0.9992\n",
      "Epoch 00004: val_acc did not improve from 0.90541\n",
      "2544/2544 [==============================] - 35s 14ms/sample - loss: 0.0521 - acc: 0.9992 - val_loss: 2.8889 - val_acc: 0.8514\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 005 data\n",
      "1(867, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 005 trainning\n",
      "Train on 2524 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2520/2524 [============================>.] - ETA: 0s - loss: 0.2000 - acc: 0.9758\n",
      "Epoch 00001: val_acc improved from -inf to 0.68919, saving model to models\\005\\005#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2524/2524 [==============================] - 36s 14ms/sample - loss: 0.1998 - acc: 0.9758 - val_loss: 3.8725 - val_acc: 0.6892\n",
      "Epoch 2/4\n",
      "2520/2524 [============================>.] - ETA: 0s - loss: 0.0197 - acc: 0.9992\n",
      "Epoch 00002: val_acc improved from 0.68919 to 0.81081, saving model to models\\005\\005#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2524/2524 [==============================] - 35s 14ms/sample - loss: 0.0197 - acc: 0.9992 - val_loss: 0.7422 - val_acc: 0.8108\n",
      "Epoch 3/4\n",
      "2520/2524 [============================>.] - ETA: 0s - loss: 0.0575 - acc: 0.9960\n",
      "Epoch 00003: val_acc did not improve from 0.81081\n",
      "2524/2524 [==============================] - 35s 14ms/sample - loss: 0.0581 - acc: 0.9960 - val_loss: 4.8003 - val_acc: 0.6351\n",
      "Epoch 4/4\n",
      "2520/2524 [============================>.] - ETA: 0s - loss: 0.2495 - acc: 0.9825\n",
      "Epoch 00004: val_acc did not improve from 0.81081\n",
      "2524/2524 [==============================] - 34s 14ms/sample - loss: 0.2492 - acc: 0.9826 - val_loss: 2.2806 - val_acc: 0.7162\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 008 data\n",
      "1(883, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 008 trainning\n",
      "Train on 2785 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2780/2785 [============================>.] - ETA: 0s - loss: 0.2643 - acc: 0.9594\n",
      "Epoch 00001: val_acc improved from -inf to 0.63514, saving model to models\\008\\008#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2785/2785 [==============================] - 40s 14ms/sample - loss: 0.2640 - acc: 0.9594 - val_loss: 6.0295 - val_acc: 0.6351\n",
      "Epoch 2/4\n",
      "2780/2785 [============================>.] - ETA: 0s - loss: 0.0152 - acc: 1.0000\n",
      "Epoch 00002: val_acc did not improve from 0.63514\n",
      "2785/2785 [==============================] - 39s 14ms/sample - loss: 0.0152 - acc: 1.0000 - val_loss: 4.6946 - val_acc: 0.6351\n",
      "Epoch 3/4\n",
      "2780/2785 [============================>.] - ETA: 0s - loss: 0.1503 - acc: 0.9806\n",
      "Epoch 00003: val_acc did not improve from 0.63514\n",
      "2785/2785 [==============================] - 38s 14ms/sample - loss: 0.1503 - acc: 0.9806 - val_loss: 10.1454 - val_acc: 0.6351\n",
      "Epoch 4/4\n",
      "2780/2785 [============================>.] - ETA: 0s - loss: 0.0679 - acc: 1.0000\n",
      "Epoch 00004: val_acc improved from 0.63514 to 0.66216, saving model to models\\008\\008#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2785/2785 [==============================] - 39s 14ms/sample - loss: 0.0678 - acc: 1.0000 - val_loss: 4.7083 - val_acc: 0.6622\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 009 data\n",
      "1(583, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 009 trainning\n",
      "Train on 1917 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "1910/1917 [============================>.] - ETA: 0s - loss: 0.3255 - acc: 0.9691\n",
      "Epoch 00001: val_acc improved from -inf to 0.64865, saving model to models\\009\\009#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1917/1917 [==============================] - 29s 15ms/sample - loss: 0.3247 - acc: 0.9692 - val_loss: 3.0004 - val_acc: 0.6486\n",
      "Epoch 2/4\n",
      "1910/1917 [============================>.] - ETA: 0s - loss: 0.0404 - acc: 0.9995\n",
      "Epoch 00002: val_acc did not improve from 0.64865\n",
      "1917/1917 [==============================] - 26s 14ms/sample - loss: 0.0403 - acc: 0.9995 - val_loss: 4.5138 - val_acc: 0.6351\n",
      "Epoch 3/4\n",
      "1910/1917 [============================>.] - ETA: 0s - loss: 0.0088 - acc: 1.0000\n",
      "Epoch 00003: val_acc improved from 0.64865 to 0.67568, saving model to models\\009\\009#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1917/1917 [==============================] - 27s 14ms/sample - loss: 0.0088 - acc: 1.0000 - val_loss: 3.2104 - val_acc: 0.6757\n",
      "Epoch 4/4\n",
      "1910/1917 [============================>.] - ETA: 0s - loss: 0.0054 - acc: 1.0000\n",
      "Epoch 00004: val_acc improved from 0.67568 to 0.75676, saving model to models\\009\\009#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1917/1917 [==============================] - 27s 14ms/sample - loss: 0.0054 - acc: 1.0000 - val_loss: 3.2692 - val_acc: 0.7568\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 010 data\n",
      "1(885, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 010 trainning\n",
      "Train on 2298 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2290/2298 [============================>.] - ETA: 0s - loss: 0.2836 - acc: 0.9380\n",
      "Epoch 00001: val_acc improved from -inf to 0.75676, saving model to models\\010\\010#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2298/2298 [==============================] - 34s 15ms/sample - loss: 0.2827 - acc: 0.9382 - val_loss: 1.1087 - val_acc: 0.7568\n",
      "Epoch 2/4\n",
      "2290/2298 [============================>.] - ETA: 0s - loss: 0.0798 - acc: 0.9873\n",
      "Epoch 00002: val_acc did not improve from 0.75676\n",
      "2298/2298 [==============================] - 31s 14ms/sample - loss: 0.0799 - acc: 0.9874 - val_loss: 2.0458 - val_acc: 0.7432\n",
      "Epoch 3/4\n",
      "2290/2298 [============================>.] - ETA: 0s - loss: 0.0357 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 0.75676\n",
      "2298/2298 [==============================] - 32s 14ms/sample - loss: 0.0356 - acc: 1.0000 - val_loss: 1.4378 - val_acc: 0.7432\n",
      "Epoch 4/4\n",
      "2290/2298 [============================>.] - ETA: 0s - loss: 0.0082 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 0.75676\n",
      "2298/2298 [==============================] - 31s 14ms/sample - loss: 0.0082 - acc: 1.0000 - val_loss: 1.2553 - val_acc: 0.7432\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 012 data\n",
      "1(888, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 012 trainning\n",
      "Train on 1877 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "1870/1877 [============================>.] - ETA: 0s - loss: 0.3688 - acc: 0.9524\n",
      "Epoch 00001: val_acc improved from -inf to 0.63514, saving model to models\\012\\012#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1877/1877 [==============================] - 28s 15ms/sample - loss: 0.3675 - acc: 0.9526 - val_loss: 2.2580 - val_acc: 0.6351\n",
      "Epoch 2/4\n",
      "1870/1877 [============================>.] - ETA: 0s - loss: 0.0132 - acc: 1.0000\n",
      "Epoch 00002: val_acc improved from 0.63514 to 0.72973, saving model to models\\012\\012#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1877/1877 [==============================] - 27s 14ms/sample - loss: 0.0132 - acc: 1.0000 - val_loss: 1.7292 - val_acc: 0.7297\n",
      "Epoch 3/4\n",
      "1870/1877 [============================>.] - ETA: 0s - loss: 0.0035 - acc: 1.0000\n",
      "Epoch 00003: val_acc improved from 0.72973 to 0.74324, saving model to models\\012\\012#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1877/1877 [==============================] - 27s 14ms/sample - loss: 0.0035 - acc: 1.0000 - val_loss: 1.7316 - val_acc: 0.7432\n",
      "Epoch 4/4\n",
      "1870/1877 [============================>.] - ETA: 0s - loss: 0.2891 - acc: 0.9786\n",
      "Epoch 00004: val_acc improved from 0.74324 to 0.94595, saving model to models\\012\\012#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1877/1877 [==============================] - 27s 14ms/sample - loss: 0.2884 - acc: 0.9787 - val_loss: 0.4276 - val_acc: 0.9459\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 013 data\n",
      "1(992, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 013 trainning\n",
      "Train on 3078 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "3070/3078 [============================>.] - ETA: 0s - loss: 0.2738 - acc: 0.9635\n",
      "Epoch 00001: val_acc improved from -inf to 0.95946, saving model to models\\013\\013#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "3078/3078 [==============================] - 44s 14ms/sample - loss: 0.2731 - acc: 0.9636 - val_loss: 0.1666 - val_acc: 0.9595\n",
      "Epoch 2/4\n",
      "3070/3078 [============================>.] - ETA: 0s - loss: 0.0650 - acc: 0.9948\n",
      "Epoch 00002: val_acc improved from 0.95946 to 0.98649, saving model to models\\013\\013#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "3078/3078 [==============================] - 43s 14ms/sample - loss: 0.0649 - acc: 0.9948 - val_loss: 0.0829 - val_acc: 0.9865\n",
      "Epoch 3/4\n",
      "3070/3078 [============================>.] - ETA: 0s - loss: 0.0060 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 0.98649\n",
      "3078/3078 [==============================] - 43s 14ms/sample - loss: 0.0060 - acc: 1.0000 - val_loss: 0.2816 - val_acc: 0.9189\n",
      "Epoch 4/4\n",
      "3070/3078 [============================>.] - ETA: 0s - loss: 0.1461 - acc: 0.9853\n",
      "Epoch 00004: val_acc did not improve from 0.98649\n",
      "3078/3078 [==============================] - 43s 14ms/sample - loss: 0.1458 - acc: 0.9854 - val_loss: 0.4440 - val_acc: 0.9324\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 015 data\n",
      "1(718, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 015 trainning\n",
      "Train on 2220 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2210/2220 [============================>.] - ETA: 0s - loss: 0.2944 - acc: 0.9629\n",
      "Epoch 00001: val_acc improved from -inf to 0.85135, saving model to models\\015\\015#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2220/2220 [==============================] - 33s 15ms/sample - loss: 0.2937 - acc: 0.9631 - val_loss: 2.5020 - val_acc: 0.8514\n",
      "Epoch 2/4\n",
      "2210/2220 [============================>.] - ETA: 0s - loss: 0.0401 - acc: 1.0000\n",
      "Epoch 00002: val_acc improved from 0.85135 to 0.86486, saving model to models\\015\\015#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2220/2220 [==============================] - 32s 14ms/sample - loss: 0.0399 - acc: 1.0000 - val_loss: 1.1571 - val_acc: 0.8649\n",
      "Epoch 3/4\n",
      "2210/2220 [============================>.] - ETA: 0s - loss: 0.1646 - acc: 0.9760\n",
      "Epoch 00003: val_acc improved from 0.86486 to 0.93243, saving model to models\\015\\015#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2220/2220 [==============================] - 31s 14ms/sample - loss: 0.1641 - acc: 0.9761 - val_loss: 0.7370 - val_acc: 0.9324\n",
      "Epoch 4/4\n",
      "2210/2220 [============================>.] - ETA: 0s - loss: 0.0259 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 0.93243\n",
      "2220/2220 [==============================] - 30s 14ms/sample - loss: 0.0258 - acc: 1.0000 - val_loss: 1.7019 - val_acc: 0.8919\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 018 data\n",
      "1(844, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 018 trainning\n",
      "Train on 1969 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "1960/1969 [============================>.] - ETA: 0s - loss: 0.2613 - acc: 0.9617\n",
      "Epoch 00001: val_acc improved from -inf to 0.87838, saving model to models\\018\\018#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1969/1969 [==============================] - 29s 15ms/sample - loss: 0.2602 - acc: 0.9619 - val_loss: 0.8666 - val_acc: 0.8784\n",
      "Epoch 2/4\n",
      "1960/1969 [============================>.] - ETA: 0s - loss: 0.0156 - acc: 1.0000\n",
      "Epoch 00002: val_acc did not improve from 0.87838\n",
      "1969/1969 [==============================] - 27s 14ms/sample - loss: 0.0156 - acc: 1.0000 - val_loss: 1.1107 - val_acc: 0.8784\n",
      "Epoch 3/4\n",
      "1960/1969 [============================>.] - ETA: 0s - loss: 0.0623 - acc: 0.9934\n",
      "Epoch 00003: val_acc did not improve from 0.87838\n",
      "1969/1969 [==============================] - 27s 14ms/sample - loss: 0.0623 - acc: 0.9934 - val_loss: 1.2302 - val_acc: 0.8784\n",
      "Epoch 4/4\n",
      "1960/1969 [============================>.] - ETA: 0s - loss: 0.0314 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 0.87838\n",
      "1969/1969 [==============================] - 27s 14ms/sample - loss: 0.0313 - acc: 1.0000 - val_loss: 1.0500 - val_acc: 0.8784\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 019 data\n",
      "1(959, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 019 trainning\n",
      "Train on 2419 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2410/2419 [============================>.] - ETA: 0s - loss: 0.2894 - acc: 0.9394\n",
      "Epoch 00001: val_acc improved from -inf to 0.94595, saving model to models\\019\\019#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2419/2419 [==============================] - 35s 14ms/sample - loss: 0.2884 - acc: 0.9396 - val_loss: 0.1758 - val_acc: 0.9459\n",
      "Epoch 2/4\n",
      "2410/2419 [============================>.] - ETA: 0s - loss: 0.2291 - acc: 0.9639\n",
      "Epoch 00002: val_acc did not improve from 0.94595\n",
      "2419/2419 [==============================] - 33s 14ms/sample - loss: 0.2286 - acc: 0.9640 - val_loss: 0.9694 - val_acc: 0.7703\n",
      "Epoch 3/4\n",
      "2410/2419 [============================>.] - ETA: 0s - loss: 0.0700 - acc: 0.9996\n",
      "Epoch 00003: val_acc did not improve from 0.94595\n",
      "2419/2419 [==============================] - 33s 14ms/sample - loss: 0.0699 - acc: 0.9996 - val_loss: 0.5647 - val_acc: 0.8108\n",
      "Epoch 4/4\n",
      "2410/2419 [============================>.] - ETA: 0s - loss: 0.0282 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 0.94595\n",
      "2419/2419 [==============================] - 33s 14ms/sample - loss: 0.0281 - acc: 1.0000 - val_loss: 0.2795 - val_acc: 0.9054\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 020 data\n",
      "1(991, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 020 trainning\n",
      "Train on 2776 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2770/2776 [============================>.] - ETA: 0s - loss: 0.2647 - acc: 0.9408\n",
      "Epoch 00001: val_acc improved from -inf to 0.89189, saving model to models\\020\\020#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2776/2776 [==============================] - 40s 14ms/sample - loss: 0.2642 - acc: 0.9409 - val_loss: 0.6265 - val_acc: 0.8919\n",
      "Epoch 2/4\n",
      "2770/2776 [============================>.] - ETA: 0s - loss: 0.0212 - acc: 0.9982\n",
      "Epoch 00002: val_acc did not improve from 0.89189\n",
      "2776/2776 [==============================] - 38s 14ms/sample - loss: 0.0212 - acc: 0.9982 - val_loss: 2.3652 - val_acc: 0.7162\n",
      "Epoch 3/4\n",
      "2770/2776 [============================>.] - ETA: 0s - loss: 0.0558 - acc: 0.9931\n",
      "Epoch 00003: val_acc did not improve from 0.89189\n",
      "2776/2776 [==============================] - 38s 14ms/sample - loss: 0.0558 - acc: 0.9932 - val_loss: 1.5249 - val_acc: 0.8649\n",
      "Epoch 4/4\n",
      "2770/2776 [============================>.] - ETA: 0s - loss: 0.0140 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 0.89189\n",
      "2776/2776 [==============================] - 38s 14ms/sample - loss: 0.0140 - acc: 1.0000 - val_loss: 0.7356 - val_acc: 0.8784\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 021 data\n",
      "1(482, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 021 trainning\n",
      "Train on 1881 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "1880/1881 [============================>.] - ETA: 0s - loss: 0.3172 - acc: 0.9590\n",
      "Epoch 00001: val_acc improved from -inf to 0.91892, saving model to models\\021\\021#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1881/1881 [==============================] - 28s 15ms/sample - loss: 0.3170 - acc: 0.9591 - val_loss: 0.6241 - val_acc: 0.9189\n",
      "Epoch 2/4\n",
      "1880/1881 [============================>.] - ETA: 0s - loss: 0.0758 - acc: 0.9920\n",
      "Epoch 00002: val_acc did not improve from 0.91892\n",
      "1881/1881 [==============================] - 26s 14ms/sample - loss: 0.0758 - acc: 0.9920 - val_loss: 1.5415 - val_acc: 0.9054\n",
      "Epoch 3/4\n",
      "1880/1881 [============================>.] - ETA: 0s - loss: 0.1184 - acc: 0.9931\n",
      "Epoch 00003: val_acc did not improve from 0.91892\n",
      "1881/1881 [==============================] - 26s 14ms/sample - loss: 0.1183 - acc: 0.9931 - val_loss: 1.0722 - val_acc: 0.9054\n",
      "Epoch 4/4\n",
      "1880/1881 [============================>.] - ETA: 0s - loss: 0.0119 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 0.91892\n",
      "1881/1881 [==============================] - 26s 14ms/sample - loss: 0.0119 - acc: 1.0000 - val_loss: 0.6333 - val_acc: 0.9189\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 023 data\n",
      "1(867, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 023 trainning\n",
      "Train on 1979 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "1970/1979 [============================>.] - ETA: 0s - loss: 0.3322 - acc: 0.9482\n",
      "Epoch 00001: val_acc improved from -inf to 0.94595, saving model to models\\023\\023#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1979/1979 [==============================] - 29s 15ms/sample - loss: 0.3309 - acc: 0.9485 - val_loss: 0.2434 - val_acc: 0.9459\n",
      "Epoch 2/4\n",
      "1970/1979 [============================>.] - ETA: 0s - loss: 0.0280 - acc: 1.0000\n",
      "Epoch 00002: val_acc did not improve from 0.94595\n",
      "1979/1979 [==============================] - 27s 14ms/sample - loss: 0.0279 - acc: 1.0000 - val_loss: 0.4199 - val_acc: 0.9054\n",
      "Epoch 3/4\n",
      "1970/1979 [============================>.] - ETA: 0s - loss: 0.0103 - acc: 1.0000\n",
      "Epoch 00003: val_acc improved from 0.94595 to 0.95946, saving model to models\\023\\023#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1979/1979 [==============================] - 28s 14ms/sample - loss: 0.0103 - acc: 1.0000 - val_loss: 0.1858 - val_acc: 0.9595\n",
      "Epoch 4/4\n",
      "1970/1979 [============================>.] - ETA: 0s - loss: 0.2853 - acc: 0.9827\n",
      "Epoch 00004: val_acc did not improve from 0.95946\n",
      "1979/1979 [==============================] - 34s 17ms/sample - loss: 0.2843 - acc: 0.9828 - val_loss: 0.3190 - val_acc: 0.9459\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 024 data\n",
      "1(848, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 024 trainning\n",
      "Train on 2553 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2550/2553 [============================>.] - ETA: 0s - loss: 0.2513 - acc: 0.9725\n",
      "Epoch 00001: val_acc improved from -inf to 0.66216, saving model to models\\024\\024#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2553/2553 [==============================] - 37s 15ms/sample - loss: 0.2510 - acc: 0.9726 - val_loss: 2.9111 - val_acc: 0.6622\n",
      "Epoch 2/4\n",
      "2550/2553 [============================>.] - ETA: 0s - loss: 0.0276 - acc: 0.9996\n",
      "Epoch 00002: val_acc did not improve from 0.66216\n",
      "2553/2553 [==============================] - 35s 14ms/sample - loss: 0.0275 - acc: 0.9996 - val_loss: 4.9223 - val_acc: 0.6486\n",
      "Epoch 3/4\n",
      "2550/2553 [============================>.] - ETA: 0s - loss: 0.0089 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 0.66216\n",
      "2553/2553 [==============================] - 35s 14ms/sample - loss: 0.0089 - acc: 1.0000 - val_loss: 5.7335 - val_acc: 0.6486\n",
      "Epoch 4/4\n",
      "2550/2553 [============================>.] - ETA: 0s - loss: 0.3713 - acc: 0.9675\n",
      "Epoch 00004: val_acc improved from 0.66216 to 0.77027, saving model to models\\024\\024#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2553/2553 [==============================] - 36s 14ms/sample - loss: 0.3713 - acc: 0.9675 - val_loss: 1.4223 - val_acc: 0.7703\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 025 data\n",
      "1(919, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 025 trainning\n",
      "Train on 2358 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2350/2358 [============================>.] - ETA: 0s - loss: 0.2582 - acc: 0.9579\n",
      "Epoch 00001: val_acc improved from -inf to 0.72973, saving model to models\\025\\025#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2358/2358 [==============================] - 34s 15ms/sample - loss: 0.2574 - acc: 0.9580 - val_loss: 1.8525 - val_acc: 0.7297\n",
      "Epoch 2/4\n",
      "2350/2358 [============================>.] - ETA: 0s - loss: 0.3008 - acc: 0.9383\n",
      "Epoch 00002: val_acc improved from 0.72973 to 0.79730, saving model to models\\025\\025#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2358/2358 [==============================] - 33s 14ms/sample - loss: 0.3000 - acc: 0.9385 - val_loss: 1.2040 - val_acc: 0.7973\n",
      "Epoch 3/4\n",
      "2350/2358 [============================>.] - ETA: 0s - loss: 0.0444 - acc: 0.9996\n",
      "Epoch 00003: val_acc did not improve from 0.79730\n",
      "2358/2358 [==============================] - 32s 14ms/sample - loss: 0.0443 - acc: 0.9996 - val_loss: 1.6079 - val_acc: 0.7838\n",
      "Epoch 4/4\n",
      "2350/2358 [============================>.] - ETA: 0s - loss: 0.0189 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 0.79730\n",
      "2358/2358 [==============================] - 33s 14ms/sample - loss: 0.0188 - acc: 1.0000 - val_loss: 1.8133 - val_acc: 0.7568\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 026 data\n",
      "1(803, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 026 trainning\n",
      "Train on 2055 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2050/2055 [============================>.] - ETA: 0s - loss: 0.3293 - acc: 0.9502\n",
      "Epoch 00001: val_acc improved from -inf to 0.63514, saving model to models\\026\\026#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2055/2055 [==============================] - 30s 15ms/sample - loss: 0.3286 - acc: 0.9504 - val_loss: 5.9199 - val_acc: 0.6351\n",
      "Epoch 2/4\n",
      "2050/2055 [============================>.] - ETA: 0s - loss: 0.0556 - acc: 0.9956\n",
      "Epoch 00002: val_acc improved from 0.63514 to 0.70270, saving model to models\\026\\026#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2055/2055 [==============================] - 29s 14ms/sample - loss: 0.0556 - acc: 0.9956 - val_loss: 4.6792 - val_acc: 0.7027\n",
      "Epoch 3/4\n",
      "2050/2055 [============================>.] - ETA: 0s - loss: 0.0114 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 0.70270\n",
      "2055/2055 [==============================] - 28s 14ms/sample - loss: 0.0114 - acc: 1.0000 - val_loss: 4.6124 - val_acc: 0.5811\n",
      "Epoch 4/4\n",
      "2050/2055 [============================>.] - ETA: 0s - loss: 0.0415 - acc: 0.9961\n",
      "Epoch 00004: val_acc did not improve from 0.70270\n",
      "2055/2055 [==============================] - 29s 14ms/sample - loss: 0.0415 - acc: 0.9961 - val_loss: 9.0470 - val_acc: 0.6081\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 027 data\n",
      "1(580, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 027 trainning\n",
      "Train on 1853 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "1850/1853 [============================>.] - ETA: 0s - loss: 0.3481 - acc: 0.9373\n",
      "Epoch 00001: val_acc improved from -inf to 0.66216, saving model to models\\027\\027#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1853/1853 [==============================] - 31s 17ms/sample - loss: 0.3476 - acc: 0.9374 - val_loss: 3.2304 - val_acc: 0.6622\n",
      "Epoch 2/4\n",
      "1850/1853 [============================>.] - ETA: 0s - loss: 0.0271 - acc: 0.9989\n",
      "Epoch 00002: val_acc improved from 0.66216 to 0.68919, saving model to models\\027\\027#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1853/1853 [==============================] - 26s 14ms/sample - loss: 0.0271 - acc: 0.9989 - val_loss: 2.5163 - val_acc: 0.6892\n",
      "Epoch 3/4\n",
      "1850/1853 [============================>.] - ETA: 0s - loss: 0.0590 - acc: 0.9886\n",
      "Epoch 00003: val_acc did not improve from 0.68919\n",
      "1853/1853 [==============================] - 26s 14ms/sample - loss: 0.0600 - acc: 0.9887 - val_loss: 0.7700 - val_acc: 0.6081\n",
      "Epoch 4/4\n",
      "1850/1853 [============================>.] - ETA: 0s - loss: 0.2234 - acc: 0.9616\n",
      "Epoch 00004: val_acc did not improve from 0.68919\n",
      "1853/1853 [==============================] - 25s 14ms/sample - loss: 0.2232 - acc: 0.9617 - val_loss: 5.4463 - val_acc: 0.6892\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 029 data\n",
      "1(765, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 029 trainning\n",
      "Train on 2180 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2170/2180 [============================>.] - ETA: 0s - loss: 0.3240 - acc: 0.9512\n",
      "Epoch 00001: val_acc improved from -inf to 0.94595, saving model to models\\029\\029#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2180/2180 [==============================] - 32s 15ms/sample - loss: 0.3230 - acc: 0.9514 - val_loss: 0.5327 - val_acc: 0.9459\n",
      "Epoch 2/4\n",
      "2170/2180 [============================>.] - ETA: 0s - loss: 0.0428 - acc: 1.0000\n",
      "Epoch 00002: val_acc did not improve from 0.94595\n",
      "2180/2180 [==============================] - 30s 14ms/sample - loss: 0.0427 - acc: 1.0000 - val_loss: 0.9968 - val_acc: 0.7973\n",
      "Epoch 3/4\n",
      "2170/2180 [============================>.] - ETA: 0s - loss: 0.0063 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 0.94595\n",
      "2180/2180 [==============================] - 30s 14ms/sample - loss: 0.0063 - acc: 1.0000 - val_loss: 0.9570 - val_acc: 0.7703\n",
      "Epoch 4/4\n",
      "2170/2180 [============================>.] - ETA: 0s - loss: 0.1073 - acc: 0.9848\n",
      "Epoch 00004: val_acc did not improve from 0.94595\n",
      "2180/2180 [==============================] - 30s 14ms/sample - loss: 0.1074 - acc: 0.9849 - val_loss: 0.9432 - val_acc: 0.8378\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 031 data\n",
      "1(648, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 031 trainning\n",
      "Train on 1932 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "1930/1932 [============================>.] - ETA: 0s - loss: 0.2882 - acc: 0.9363\n",
      "Epoch 00001: val_acc improved from -inf to 0.72973, saving model to models\\031\\031#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1932/1932 [==============================] - 29s 15ms/sample - loss: 0.2879 - acc: 0.9363 - val_loss: 2.7147 - val_acc: 0.7297\n",
      "Epoch 2/4\n",
      "1930/1932 [============================>.] - ETA: 0s - loss: 0.1324 - acc: 0.9762\n",
      "Epoch 00002: val_acc improved from 0.72973 to 0.81081, saving model to models\\031\\031#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1932/1932 [==============================] - 27s 14ms/sample - loss: 0.1324 - acc: 0.9762 - val_loss: 0.8724 - val_acc: 0.8108\n",
      "Epoch 3/4\n",
      "1930/1932 [============================>.] - ETA: 0s - loss: 0.0288 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 0.81081\n",
      "1932/1932 [==============================] - 26s 14ms/sample - loss: 0.0288 - acc: 1.0000 - val_loss: 2.0445 - val_acc: 0.7568\n",
      "Epoch 4/4\n",
      "1930/1932 [============================>.] - ETA: 0s - loss: 0.0624 - acc: 0.9891\n",
      "Epoch 00004: val_acc did not improve from 0.81081\n",
      "1932/1932 [==============================] - 26s 14ms/sample - loss: 0.0624 - acc: 0.9891 - val_loss: 1.9498 - val_acc: 0.7568\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 036 data\n",
      "1(581, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 036 trainning\n",
      "Train on 2325 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2320/2325 [============================>.] - ETA: 0s - loss: 0.2624 - acc: 0.9724\n",
      "Epoch 00001: val_acc improved from -inf to 0.91892, saving model to models\\036\\036#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2325/2325 [==============================] - 33s 14ms/sample - loss: 0.2624 - acc: 0.9725 - val_loss: 1.0321 - val_acc: 0.9189\n",
      "Epoch 2/4\n",
      "2320/2325 [============================>.] - ETA: 0s - loss: 0.0540 - acc: 1.0000\n",
      "Epoch 00002: val_acc did not improve from 0.91892\n",
      "2325/2325 [==============================] - 32s 14ms/sample - loss: 0.0539 - acc: 1.0000 - val_loss: 0.7193 - val_acc: 0.9189\n",
      "Epoch 3/4\n",
      "2320/2325 [============================>.] - ETA: 0s - loss: 0.0036 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 0.91892\n",
      "2325/2325 [==============================] - 32s 14ms/sample - loss: 0.0036 - acc: 1.0000 - val_loss: 0.9402 - val_acc: 0.9189\n",
      "Epoch 4/4\n",
      "2320/2325 [============================>.] - ETA: 0s - loss: 0.1329 - acc: 0.9966\n",
      "Epoch 00004: val_acc did not improve from 0.91892\n",
      "2325/2325 [==============================] - 34s 15ms/sample - loss: 0.1328 - acc: 0.9966 - val_loss: 1.8527 - val_acc: 0.9189\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 037 data\n",
      "1(653, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 037 trainning\n",
      "Train on 2284 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2280/2284 [============================>.] - ETA: 0s - loss: 0.3318 - acc: 0.9211\n",
      "Epoch 00001: val_acc improved from -inf to 1.00000, saving model to models\\037\\037#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2284/2284 [==============================] - 35s 16ms/sample - loss: 0.3313 - acc: 0.9212 - val_loss: 0.0125 - val_acc: 1.0000\n",
      "Epoch 2/4\n",
      "2280/2284 [============================>.] - ETA: 0s - loss: 0.0508 - acc: 0.9939\n",
      "Epoch 00002: val_acc did not improve from 1.00000\n",
      "2284/2284 [==============================] - 31s 14ms/sample - loss: 0.0507 - acc: 0.9939 - val_loss: 0.0156 - val_acc: 1.0000\n",
      "Epoch 3/4\n",
      "2280/2284 [============================>.] - ETA: 0s - loss: 0.2601 - acc: 0.9785\n",
      "Epoch 00003: val_acc did not improve from 1.00000\n",
      "2284/2284 [==============================] - 31s 14ms/sample - loss: 0.2598 - acc: 0.9785 - val_loss: 0.0841 - val_acc: 1.0000\n",
      "Epoch 4/4\n",
      "2280/2284 [============================>.] - ETA: 0s - loss: 0.0542 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 1.00000\n",
      "2284/2284 [==============================] - 32s 14ms/sample - loss: 0.0542 - acc: 1.0000 - val_loss: 0.0343 - val_acc: 1.0000\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 039 data\n",
      "1(658, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 039 trainning\n",
      "Train on 2177 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2170/2177 [============================>.] - ETA: 0s - loss: 0.3519 - acc: 0.9687\n",
      "Epoch 00001: val_acc improved from -inf to 0.97297, saving model to models\\039\\039#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2177/2177 [==============================] - 32s 15ms/sample - loss: 0.3511 - acc: 0.9688 - val_loss: 0.1528 - val_acc: 0.9730\n",
      "Epoch 2/4\n",
      "2170/2177 [============================>.] - ETA: 0s - loss: 0.0678 - acc: 0.9876\n",
      "Epoch 00002: val_acc did not improve from 0.97297\n",
      "2177/2177 [==============================] - 30s 14ms/sample - loss: 0.0691 - acc: 0.9871 - val_loss: 0.5540 - val_acc: 0.7973\n",
      "Epoch 3/4\n",
      "2170/2177 [============================>.] - ETA: 0s - loss: 0.1835 - acc: 0.9931\n",
      "Epoch 00003: val_acc did not improve from 0.97297\n",
      "2177/2177 [==============================] - 30s 14ms/sample - loss: 0.1832 - acc: 0.9931 - val_loss: 0.2934 - val_acc: 0.8378\n",
      "Epoch 4/4\n",
      "2170/2177 [============================>.] - ETA: 0s - loss: 0.0409 - acc: 0.9991\n",
      "Epoch 00004: val_acc did not improve from 0.97297\n",
      "2177/2177 [==============================] - 30s 14ms/sample - loss: 0.0409 - acc: 0.9991 - val_loss: 0.0664 - val_acc: 0.9595\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 043 data\n",
      "1(544, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 043 trainning\n",
      "Train on 2175 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2170/2175 [============================>.] - ETA: 0s - loss: 0.2524 - acc: 0.9687\n",
      "Epoch 00001: val_acc improved from -inf to 1.00000, saving model to models\\043\\043#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2175/2175 [==============================] - 32s 15ms/sample - loss: 0.2519 - acc: 0.9687 - val_loss: 0.0216 - val_acc: 1.0000\n",
      "Epoch 2/4\n",
      "2170/2175 [============================>.] - ETA: 0s - loss: 0.0093 - acc: 1.0000\n",
      "Epoch 00002: val_acc did not improve from 1.00000\n",
      "2175/2175 [==============================] - 30s 14ms/sample - loss: 0.0093 - acc: 1.0000 - val_loss: 0.0030 - val_acc: 1.0000\n",
      "Epoch 3/4\n",
      "2170/2175 [============================>.] - ETA: 0s - loss: 0.1968 - acc: 0.9922\n",
      "Epoch 00003: val_acc did not improve from 1.00000\n",
      "2175/2175 [==============================] - 30s 14ms/sample - loss: 0.1966 - acc: 0.9922 - val_loss: 0.0950 - val_acc: 1.0000\n",
      "Epoch 4/4\n",
      "2170/2175 [============================>.] - ETA: 0s - loss: 0.0486 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 1.00000\n",
      "2175/2175 [==============================] - 30s 14ms/sample - loss: 0.0486 - acc: 1.0000 - val_loss: 0.0219 - val_acc: 1.0000\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 044 data\n",
      "1(491, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 044 trainning\n",
      "Train on 2296 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2290/2296 [============================>.] - ETA: 0s - loss: 0.2774 - acc: 0.9616\n",
      "Epoch 00001: val_acc improved from -inf to 1.00000, saving model to models\\044\\044#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2296/2296 [==============================] - 33s 14ms/sample - loss: 0.2768 - acc: 0.9617 - val_loss: 0.0510 - val_acc: 1.0000\n",
      "Epoch 2/4\n",
      "2290/2296 [============================>.] - ETA: 0s - loss: 0.0164 - acc: 1.0000\n",
      "Epoch 00002: val_acc did not improve from 1.00000\n",
      "2296/2296 [==============================] - 31s 14ms/sample - loss: 0.0164 - acc: 1.0000 - val_loss: 0.0031 - val_acc: 1.0000\n",
      "Epoch 3/4\n",
      "2290/2296 [============================>.] - ETA: 0s - loss: 0.0026 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 1.00000\n",
      "2296/2296 [==============================] - 31s 14ms/sample - loss: 0.0026 - acc: 1.0000 - val_loss: 0.0015 - val_acc: 1.0000\n",
      "Epoch 4/4\n",
      "2290/2296 [============================>.] - ETA: 0s - loss: 0.1870 - acc: 0.9751\n",
      "Epoch 00004: val_acc did not improve from 1.00000\n",
      "2296/2296 [==============================] - 31s 14ms/sample - loss: 0.1866 - acc: 0.9752 - val_loss: 0.0897 - val_acc: 0.9865\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 048 data\n",
      "1(479, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 048 trainning\n",
      "Train on 2451 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2450/2451 [============================>.] - ETA: 0s - loss: 0.2952 - acc: 0.9555\n",
      "Epoch 00001: val_acc improved from -inf to 1.00000, saving model to models\\048\\048#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2451/2451 [==============================] - 35s 14ms/sample - loss: 0.2951 - acc: 0.9555 - val_loss: 0.0264 - val_acc: 1.0000\n",
      "Epoch 2/4\n",
      "2450/2451 [============================>.] - ETA: 0s - loss: 0.0460 - acc: 0.9927\n",
      "Epoch 00002: val_acc did not improve from 1.00000\n",
      "2451/2451 [==============================] - 34s 14ms/sample - loss: 0.0460 - acc: 0.9927 - val_loss: 0.1065 - val_acc: 1.0000\n",
      "Epoch 3/4\n",
      "2450/2451 [============================>.] - ETA: 0s - loss: 0.0394 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 1.00000\n",
      "2451/2451 [==============================] - 33s 14ms/sample - loss: 0.0394 - acc: 1.0000 - val_loss: 0.0222 - val_acc: 1.0000\n",
      "Epoch 4/4\n",
      "2450/2451 [============================>.] - ETA: 0s - loss: 0.0084 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 1.00000\n",
      "2451/2451 [==============================] - 33s 14ms/sample - loss: 0.0084 - acc: 1.0000 - val_loss: 0.0127 - val_acc: 1.0000\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 049 data\n",
      "1(590, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 049 trainning\n",
      "Train on 2149 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2140/2149 [============================>.] - ETA: 0s - loss: 0.2642 - acc: 0.9575\n",
      "Epoch 00001: val_acc improved from -inf to 0.98649, saving model to models\\049\\049#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2149/2149 [==============================] - 31s 15ms/sample - loss: 0.2632 - acc: 0.9577 - val_loss: 0.1227 - val_acc: 0.9865\n",
      "Epoch 2/4\n",
      "2140/2149 [============================>.] - ETA: 0s - loss: 0.0603 - acc: 0.9958\n",
      "Epoch 00002: val_acc did not improve from 0.98649\n",
      "2149/2149 [==============================] - 30s 14ms/sample - loss: 0.0601 - acc: 0.9958 - val_loss: 0.1010 - val_acc: 0.9865\n",
      "Epoch 3/4\n",
      "2140/2149 [============================>.] - ETA: 0s - loss: 0.0356 - acc: 0.9977\n",
      "Epoch 00003: val_acc did not improve from 0.98649\n",
      "2149/2149 [==============================] - 30s 14ms/sample - loss: 0.0355 - acc: 0.9977 - val_loss: 0.3609 - val_acc: 0.8784\n",
      "Epoch 4/4\n",
      "2140/2149 [============================>.] - ETA: 0s - loss: 0.0526 - acc: 0.9967\n",
      "Epoch 00004: val_acc did not improve from 0.98649\n",
      "2149/2149 [==============================] - 29s 14ms/sample - loss: 0.0526 - acc: 0.9967 - val_loss: 0.3678 - val_acc: 0.9865\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 050 data\n",
      "1(643, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 050 trainning\n",
      "Train on 2160 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2150/2160 [============================>.] - ETA: 0s - loss: 0.2259 - acc: 0.9679\n",
      "Epoch 00001: val_acc improved from -inf to 1.00000, saving model to models\\050\\050#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2160/2160 [==============================] - 31s 15ms/sample - loss: 0.2252 - acc: 0.9681 - val_loss: 0.0778 - val_acc: 1.0000\n",
      "Epoch 2/4\n",
      "2150/2160 [============================>.] - ETA: 0s - loss: 0.0171 - acc: 1.0000\n",
      "Epoch 00002: val_acc did not improve from 1.00000\n",
      "2160/2160 [==============================] - 30s 14ms/sample - loss: 0.0171 - acc: 1.0000 - val_loss: 0.0127 - val_acc: 1.0000\n",
      "Epoch 3/4\n",
      "2150/2160 [============================>.] - ETA: 0s - loss: 0.1176 - acc: 0.9907\n",
      "Epoch 00003: val_acc did not improve from 1.00000\n",
      "2160/2160 [==============================] - 30s 14ms/sample - loss: 0.1172 - acc: 0.9907 - val_loss: 0.0712 - val_acc: 0.9865\n",
      "Epoch 4/4\n",
      "2150/2160 [============================>.] - ETA: 0s - loss: 0.0101 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 1.00000\n",
      "2160/2160 [==============================] - 30s 14ms/sample - loss: 0.0101 - acc: 1.0000 - val_loss: 0.0233 - val_acc: 0.9865\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 052 data\n",
      "1(526, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 052 trainning\n",
      "Train on 2247 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2240/2247 [============================>.] - ETA: 0s - loss: 0.2642 - acc: 0.9607\n",
      "Epoch 00001: val_acc improved from -inf to 1.00000, saving model to models\\052\\052#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2247/2247 [==============================] - 33s 15ms/sample - loss: 0.2635 - acc: 0.9608 - val_loss: 0.0315 - val_acc: 1.0000\n",
      "Epoch 2/4\n",
      "2240/2247 [============================>.] - ETA: 0s - loss: 0.0423 - acc: 0.9960\n",
      "Epoch 00002: val_acc did not improve from 1.00000\n",
      "2247/2247 [==============================] - 31s 14ms/sample - loss: 0.0424 - acc: 0.9960 - val_loss: 0.0638 - val_acc: 1.0000\n",
      "Epoch 3/4\n",
      "2240/2247 [============================>.] - ETA: 0s - loss: 0.0173 - acc: 0.9996\n",
      "Epoch 00003: val_acc did not improve from 1.00000\n",
      "2247/2247 [==============================] - 31s 14ms/sample - loss: 0.0173 - acc: 0.9996 - val_loss: 0.0039 - val_acc: 1.0000\n",
      "Epoch 4/4\n",
      "2240/2247 [============================>.] - ETA: 0s - loss: 0.0117 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 1.00000\n",
      "2247/2247 [==============================] - 31s 14ms/sample - loss: 0.0118 - acc: 1.0000 - val_loss: 0.0263 - val_acc: 1.0000\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 053 data\n",
      "1(522, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 053 trainning\n",
      "Train on 1971 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "1970/1971 [============================>.] - ETA: 0s - loss: 0.3389 - acc: 0.9472\n",
      "Epoch 00001: val_acc improved from -inf to 0.94595, saving model to models\\053\\053#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1971/1971 [==============================] - 30s 15ms/sample - loss: 0.3388 - acc: 0.9472 - val_loss: 0.1370 - val_acc: 0.9459\n",
      "Epoch 2/4\n",
      "1970/1971 [============================>.] - ETA: 0s - loss: 0.0254 - acc: 0.9990\n",
      "Epoch 00002: val_acc improved from 0.94595 to 1.00000, saving model to models\\053\\053#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1971/1971 [==============================] - 28s 14ms/sample - loss: 0.0253 - acc: 0.9990 - val_loss: 0.0056 - val_acc: 1.0000\n",
      "Epoch 3/4\n",
      "1970/1971 [============================>.] - ETA: 0s - loss: 0.1675 - acc: 0.9782\n",
      "Epoch 00003: val_acc did not improve from 1.00000\n",
      "1971/1971 [==============================] - 27s 14ms/sample - loss: 0.1674 - acc: 0.9782 - val_loss: 0.0763 - val_acc: 1.0000\n",
      "Epoch 4/4\n",
      "1970/1971 [============================>.] - ETA: 0s - loss: 0.0440 - acc: 0.9995\n",
      "Epoch 00004: val_acc did not improve from 1.00000\n",
      "1971/1971 [==============================] - 27s 14ms/sample - loss: 0.0440 - acc: 0.9995 - val_loss: 0.0189 - val_acc: 1.0000\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 057 data\n",
      "1(614, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 057 trainning\n",
      "Train on 1902 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "1900/1902 [============================>.] - ETA: 0s - loss: 0.2445 - acc: 0.9658\n",
      "Epoch 00001: val_acc improved from -inf to 1.00000, saving model to models\\057\\057#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1902/1902 [==============================] - 29s 15ms/sample - loss: 0.2442 - acc: 0.9658 - val_loss: 0.0112 - val_acc: 1.0000\n",
      "Epoch 2/4\n",
      "1900/1902 [============================>.] - ETA: 0s - loss: 0.0833 - acc: 0.9916\n",
      "Epoch 00002: val_acc did not improve from 1.00000\n",
      "1902/1902 [==============================] - 27s 14ms/sample - loss: 0.0832 - acc: 0.9916 - val_loss: 0.0055 - val_acc: 1.0000\n",
      "Epoch 3/4\n",
      "1900/1902 [============================>.] - ETA: 0s - loss: 0.0949 - acc: 0.9953\n",
      "Epoch 00003: val_acc did not improve from 1.00000\n",
      "1902/1902 [==============================] - 27s 14ms/sample - loss: 0.0949 - acc: 0.9953 - val_loss: 0.1129 - val_acc: 1.0000\n",
      "Epoch 4/4\n",
      "1900/1902 [============================>.] - ETA: 0s - loss: 0.1370 - acc: 0.9889\n",
      "Epoch 00004: val_acc did not improve from 1.00000\n",
      "1902/1902 [==============================] - 27s 14ms/sample - loss: 0.1371 - acc: 0.9890 - val_loss: 0.2798 - val_acc: 1.0000\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 059 data\n",
      "1(630, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 059 trainning\n",
      "Train on 2363 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2360/2363 [============================>.] - ETA: 0s - loss: 0.2546 - acc: 0.9665\n",
      "Epoch 00001: val_acc improved from -inf to 0.98649, saving model to models\\059\\059#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2363/2363 [==============================] - 35s 15ms/sample - loss: 0.2543 - acc: 0.9666 - val_loss: 0.1610 - val_acc: 0.9865\n",
      "Epoch 2/4\n",
      "2360/2363 [============================>.] - ETA: 0s - loss: 0.0935 - acc: 0.9915\n",
      "Epoch 00002: val_acc improved from 0.98649 to 1.00000, saving model to models\\059\\059#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2363/2363 [==============================] - 34s 14ms/sample - loss: 0.0934 - acc: 0.9915 - val_loss: 0.0768 - val_acc: 1.0000\n",
      "Epoch 3/4\n",
      "2360/2363 [============================>.] - ETA: 0s - loss: 0.0407 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 1.00000\n",
      "2363/2363 [==============================] - 33s 14ms/sample - loss: 0.0406 - acc: 1.0000 - val_loss: 0.0223 - val_acc: 1.0000\n",
      "Epoch 4/4\n",
      "2360/2363 [============================>.] - ETA: 0s - loss: 0.0442 - acc: 0.9949\n",
      "Epoch 00004: val_acc did not improve from 1.00000\n",
      "2363/2363 [==============================] - 33s 14ms/sample - loss: 0.0442 - acc: 0.9949 - val_loss: 0.0209 - val_acc: 1.0000\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 061 data\n",
      "1(458, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 061 trainning\n",
      "Train on 1768 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "1760/1768 [============================>.] - ETA: 0s - loss: 0.4224 - acc: 0.9011\n",
      "Epoch 00001: val_acc improved from -inf to 1.00000, saving model to models\\061\\061#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1768/1768 [==============================] - 27s 15ms/sample - loss: 0.4206 - acc: 0.9016 - val_loss: 0.0381 - val_acc: 1.0000\n",
      "Epoch 2/4\n",
      "1760/1768 [============================>.] - ETA: 0s - loss: 0.1559 - acc: 0.9898\n",
      "Epoch 00002: val_acc did not improve from 1.00000\n",
      "1768/1768 [==============================] - 25s 14ms/sample - loss: 0.1554 - acc: 0.9898 - val_loss: 0.0540 - val_acc: 1.0000\n",
      "Epoch 3/4\n",
      "1760/1768 [============================>.] - ETA: 0s - loss: 0.0271 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 1.00000\n",
      "1768/1768 [==============================] - 25s 14ms/sample - loss: 0.0270 - acc: 1.0000 - val_loss: 0.0115 - val_acc: 1.0000\n",
      "Epoch 4/4\n",
      "1760/1768 [============================>.] - ETA: 0s - loss: 0.0064 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 1.00000\n",
      "1768/1768 [==============================] - 25s 14ms/sample - loss: 0.0064 - acc: 1.0000 - val_loss: 0.0032 - val_acc: 1.0000\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 064 data\n",
      "1(171, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 064 trainning\n",
      "Train on 1392 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "1390/1392 [============================>.] - ETA: 0s - loss: 0.3465 - acc: 0.9424\n",
      "Epoch 00001: val_acc improved from -inf to 0.97297, saving model to models\\064\\064#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1392/1392 [==============================] - 22s 15ms/sample - loss: 0.3460 - acc: 0.9425 - val_loss: 0.1433 - val_acc: 0.9730\n",
      "Epoch 2/4\n",
      "1390/1392 [============================>.] - ETA: 0s - loss: 0.1146 - acc: 0.9799\n",
      "Epoch 00002: val_acc improved from 0.97297 to 0.98649, saving model to models\\064\\064#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1392/1392 [==============================] - 20s 15ms/sample - loss: 0.1145 - acc: 0.9799 - val_loss: 0.0764 - val_acc: 0.9865\n",
      "Epoch 3/4\n",
      "1390/1392 [============================>.] - ETA: 0s - loss: 0.0539 - acc: 0.9914\n",
      "Epoch 00003: val_acc did not improve from 0.98649\n",
      "1392/1392 [==============================] - 20s 14ms/sample - loss: 0.0538 - acc: 0.9914 - val_loss: 0.0728 - val_acc: 0.9865\n",
      "Epoch 4/4\n",
      "1390/1392 [============================>.] - ETA: 0s - loss: 0.0555 - acc: 0.9914\n",
      "Epoch 00004: val_acc improved from 0.98649 to 1.00000, saving model to models\\064\\064#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1392/1392 [==============================] - 20s 14ms/sample - loss: 0.0555 - acc: 0.9914 - val_loss: 0.0157 - val_acc: 1.0000\n",
      "49559\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 065 data\n",
      "1(455, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 065 trainning\n",
      "Train on 1995 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "1990/1995 [============================>.] - ETA: 0s - loss: 0.3595 - acc: 0.9347\n",
      "Epoch 00001: val_acc improved from -inf to 0.98649, saving model to models\\065\\065#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1995/1995 [==============================] - 29s 15ms/sample - loss: 0.3586 - acc: 0.9348 - val_loss: 0.0463 - val_acc: 0.9865\n",
      "Epoch 2/4\n",
      "1990/1995 [============================>.] - ETA: 0s - loss: 0.0813 - acc: 0.9879\n",
      "Epoch 00002: val_acc improved from 0.98649 to 1.00000, saving model to models\\065\\065#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1995/1995 [==============================] - 29s 14ms/sample - loss: 0.0811 - acc: 0.9880 - val_loss: 0.0131 - val_acc: 1.0000\n",
      "Epoch 3/4\n",
      "1990/1995 [============================>.] - ETA: 0s - loss: 0.0265 - acc: 0.9980\n",
      "Epoch 00003: val_acc did not improve from 1.00000\n",
      "1995/1995 [==============================] - 28s 14ms/sample - loss: 0.0264 - acc: 0.9980 - val_loss: 0.0089 - val_acc: 1.0000\n",
      "Epoch 4/4\n",
      "1990/1995 [============================>.] - ETA: 0s - loss: 0.0057 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 1.00000\n",
      "1995/1995 [==============================] - 28s 14ms/sample - loss: 0.0057 - acc: 1.0000 - val_loss: 0.0024 - val_acc: 1.0000\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 066 data\n",
      "1(651, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 066 trainning\n",
      "Train on 2499 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2490/2499 [============================>.] - ETA: 0s - loss: 0.3651 - acc: 0.9257\n",
      "Epoch 00001: val_acc improved from -inf to 0.98649, saving model to models\\066\\066#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2499/2499 [==============================] - 36s 14ms/sample - loss: 0.3641 - acc: 0.9260 - val_loss: 0.0914 - val_acc: 0.9865\n",
      "Epoch 2/4\n",
      "2490/2499 [============================>.] - ETA: 0s - loss: 0.0441 - acc: 0.9948\n",
      "Epoch 00002: val_acc did not improve from 0.98649\n",
      "2499/2499 [==============================] - 34s 14ms/sample - loss: 0.0445 - acc: 0.9948 - val_loss: 0.1677 - val_acc: 0.9730\n",
      "Epoch 3/4\n",
      "2490/2499 [============================>.] - ETA: 0s - loss: 0.0705 - acc: 0.9952\n",
      "Epoch 00003: val_acc did not improve from 0.98649\n",
      "2499/2499 [==============================] - 34s 14ms/sample - loss: 0.0704 - acc: 0.9952 - val_loss: 0.0481 - val_acc: 0.9865\n",
      "Epoch 4/4\n",
      "2490/2499 [============================>.] - ETA: 0s - loss: 0.0118 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 0.98649\n",
      "2499/2499 [==============================] - 35s 14ms/sample - loss: 0.0118 - acc: 1.0000 - val_loss: 0.0232 - val_acc: 0.9865\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 067 data\n",
      "1(518, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 067 trainning\n",
      "Train on 2317 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2310/2317 [============================>.] - ETA: 0s - loss: 0.2152 - acc: 0.9658\n",
      "Epoch 00001: val_acc improved from -inf to 0.94595, saving model to models\\067\\067#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2317/2317 [==============================] - 35s 15ms/sample - loss: 0.2148 - acc: 0.9659 - val_loss: 0.2762 - val_acc: 0.9459\n",
      "Epoch 2/4\n",
      "2310/2317 [============================>.] - ETA: 0s - loss: 0.0771 - acc: 0.9961\n",
      "Epoch 00002: val_acc improved from 0.94595 to 0.98649, saving model to models\\067\\067#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2317/2317 [==============================] - 33s 14ms/sample - loss: 0.0769 - acc: 0.9961 - val_loss: 0.0924 - val_acc: 0.9865\n",
      "Epoch 3/4\n",
      "2310/2317 [============================>.] - ETA: 0s - loss: 0.0091 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 0.98649\n",
      "2317/2317 [==============================] - 35s 15ms/sample - loss: 0.0091 - acc: 1.0000 - val_loss: 0.0671 - val_acc: 0.9865\n",
      "Epoch 4/4\n",
      "2310/2317 [============================>.] - ETA: 0s - loss: 0.0017 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 0.98649\n",
      "2317/2317 [==============================] - 33s 14ms/sample - loss: 0.0017 - acc: 1.0000 - val_loss: 0.0634 - val_acc: 0.9865\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 071 data\n",
      "1(518, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 071 trainning\n",
      "Train on 2222 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2220/2222 [============================>.] - ETA: 0s - loss: 0.2736 - acc: 0.9563\n",
      "Epoch 00001: val_acc improved from -inf to 0.98649, saving model to models\\071\\071#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2222/2222 [==============================] - 32s 14ms/sample - loss: 0.2734 - acc: 0.9563 - val_loss: 0.0438 - val_acc: 0.9865\n",
      "Epoch 2/4\n",
      "2220/2222 [============================>.] - ETA: 0s - loss: 0.0763 - acc: 0.9883\n",
      "Epoch 00002: val_acc did not improve from 0.98649\n",
      "2222/2222 [==============================] - 30s 14ms/sample - loss: 0.0763 - acc: 0.9883 - val_loss: 0.1862 - val_acc: 0.9865\n",
      "Epoch 3/4\n",
      "2220/2222 [============================>.] - ETA: 0s - loss: 0.0535 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 0.98649\n",
      "2222/2222 [==============================] - 30s 14ms/sample - loss: 0.0535 - acc: 1.0000 - val_loss: 0.2076 - val_acc: 0.9865\n",
      "Epoch 4/4\n",
      "2220/2222 [============================>.] - ETA: 0s - loss: 0.0179 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 0.98649\n",
      "2222/2222 [==============================] - 30s 14ms/sample - loss: 0.0179 - acc: 1.0000 - val_loss: 0.1917 - val_acc: 0.9865\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 073 data\n",
      "1(537, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 073 trainning\n",
      "Train on 1865 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "1860/1865 [============================>.] - ETA: 0s - loss: 0.2986 - acc: 0.9489\n",
      "Epoch 00001: val_acc improved from -inf to 1.00000, saving model to models\\073\\073#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1865/1865 [==============================] - 28s 15ms/sample - loss: 0.2979 - acc: 0.9491 - val_loss: 0.0298 - val_acc: 1.0000\n",
      "Epoch 2/4\n",
      "1860/1865 [============================>.] - ETA: 0s - loss: 0.0691 - acc: 0.9909\n",
      "Epoch 00002: val_acc did not improve from 1.00000\n",
      "1865/1865 [==============================] - 26s 14ms/sample - loss: 0.0689 - acc: 0.9909 - val_loss: 0.0127 - val_acc: 1.0000\n",
      "Epoch 3/4\n",
      "1860/1865 [============================>.] - ETA: 0s - loss: 0.0084 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 1.00000\n",
      "1865/1865 [==============================] - 26s 14ms/sample - loss: 0.0084 - acc: 1.0000 - val_loss: 0.0036 - val_acc: 1.0000\n",
      "Epoch 4/4\n",
      "1860/1865 [============================>.] - ETA: 0s - loss: 0.0029 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 1.00000\n",
      "1865/1865 [==============================] - 26s 14ms/sample - loss: 0.0029 - acc: 1.0000 - val_loss: 0.0012 - val_acc: 1.0000\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 075 data\n",
      "1(632, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 075 trainning\n",
      "Train on 2957 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2950/2957 [============================>.] - ETA: 0s - loss: 0.2123 - acc: 0.9715\n",
      "Epoch 00001: val_acc improved from -inf to 1.00000, saving model to models\\075\\075#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2957/2957 [==============================] - 42s 14ms/sample - loss: 0.2119 - acc: 0.9716 - val_loss: 0.0565 - val_acc: 1.0000\n",
      "Epoch 2/4\n",
      "2950/2957 [============================>.] - ETA: 0s - loss: 0.0194 - acc: 0.9986\n",
      "Epoch 00002: val_acc did not improve from 1.00000\n",
      "2957/2957 [==============================] - 41s 14ms/sample - loss: 0.0195 - acc: 0.9986 - val_loss: 0.6400 - val_acc: 0.7568\n",
      "Epoch 3/4\n",
      "2950/2957 [============================>.] - ETA: 0s - loss: 0.1516 - acc: 0.9878\n",
      "Epoch 00003: val_acc did not improve from 1.00000\n",
      "2957/2957 [==============================] - 41s 14ms/sample - loss: 0.1514 - acc: 0.9878 - val_loss: 0.0697 - val_acc: 1.0000\n",
      "Epoch 4/4\n",
      "2950/2957 [============================>.] - ETA: 0s - loss: 0.0794 - acc: 0.9969\n",
      "Epoch 00004: val_acc did not improve from 1.00000\n",
      "2957/2957 [==============================] - 41s 14ms/sample - loss: 0.0793 - acc: 0.9970 - val_loss: 0.0240 - val_acc: 1.0000\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 079 data\n",
      "1(559, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 079 trainning\n",
      "Train on 2051 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2050/2051 [============================>.] - ETA: 0s - loss: 0.4062 - acc: 0.9278\n",
      "Epoch 00001: val_acc improved from -inf to 0.98649, saving model to models\\079\\079#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2051/2051 [==============================] - 30s 15ms/sample - loss: 0.4060 - acc: 0.9278 - val_loss: 0.0843 - val_acc: 0.9865\n",
      "Epoch 2/4\n",
      "2050/2051 [============================>.] - ETA: 0s - loss: 0.0353 - acc: 0.9990\n",
      "Epoch 00002: val_acc did not improve from 0.98649\n",
      "2051/2051 [==============================] - 29s 14ms/sample - loss: 0.0353 - acc: 0.9990 - val_loss: 0.0873 - val_acc: 0.9865\n",
      "Epoch 3/4\n",
      "2050/2051 [============================>.] - ETA: 0s - loss: 0.0073 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 0.98649\n",
      "2051/2051 [==============================] - 28s 14ms/sample - loss: 0.0073 - acc: 1.0000 - val_loss: 0.0149 - val_acc: 0.9865\n",
      "Epoch 4/4\n",
      "2050/2051 [============================>.] - ETA: 0s - loss: 0.0034 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 0.98649\n",
      "2051/2051 [==============================] - 28s 14ms/sample - loss: 0.0034 - acc: 1.0000 - val_loss: 0.0268 - val_acc: 0.9865\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 082 data\n",
      "1(782, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 082 trainning\n",
      "Train on 2421 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2420/2421 [============================>.] - ETA: 0s - loss: 0.2413 - acc: 0.9562\n",
      "Epoch 00001: val_acc improved from -inf to 0.98649, saving model to models\\082\\082#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2421/2421 [==============================] - 35s 15ms/sample - loss: 0.2412 - acc: 0.9562 - val_loss: 0.0466 - val_acc: 0.9865\n",
      "Epoch 2/4\n",
      "2420/2421 [============================>.] - ETA: 0s - loss: 0.0235 - acc: 0.9988\n",
      "Epoch 00002: val_acc did not improve from 0.98649\n",
      "2421/2421 [==============================] - 33s 14ms/sample - loss: 0.0235 - acc: 0.9988 - val_loss: 0.0371 - val_acc: 0.9865\n",
      "Epoch 3/4\n",
      "2420/2421 [============================>.] - ETA: 0s - loss: 0.3323 - acc: 0.9715\n",
      "Epoch 00003: val_acc did not improve from 0.98649\n",
      "2421/2421 [==============================] - 34s 14ms/sample - loss: 0.3322 - acc: 0.9715 - val_loss: 0.1131 - val_acc: 0.9865\n",
      "Epoch 4/4\n",
      "2420/2421 [============================>.] - ETA: 0s - loss: 0.1597 - acc: 0.9955\n",
      "Epoch 00004: val_acc did not improve from 0.98649\n",
      "2421/2421 [==============================] - 33s 14ms/sample - loss: 0.1597 - acc: 0.9955 - val_loss: 0.1131 - val_acc: 0.9865\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 083 data\n",
      "1(375, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 083 trainning\n",
      "Train on 1640 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "1630/1640 [============================>.] - ETA: 0s - loss: 0.3581 - acc: 0.9423\n",
      "Epoch 00001: val_acc improved from -inf to 0.98649, saving model to models\\083\\083#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "1640/1640 [==============================] - 24s 15ms/sample - loss: 0.3563 - acc: 0.9427 - val_loss: 0.1043 - val_acc: 0.9865\n",
      "Epoch 2/4\n",
      "1630/1640 [============================>.] - ETA: 0s - loss: 0.0266 - acc: 1.0000\n",
      "Epoch 00002: val_acc did not improve from 0.98649\n",
      "1640/1640 [==============================] - 23s 14ms/sample - loss: 0.0267 - acc: 1.0000 - val_loss: 0.2154 - val_acc: 0.9865\n",
      "Epoch 3/4\n",
      "1630/1640 [============================>.] - ETA: 0s - loss: 0.0198 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 0.98649\n",
      "1640/1640 [==============================] - 23s 14ms/sample - loss: 0.0197 - acc: 1.0000 - val_loss: 0.1321 - val_acc: 0.9865\n",
      "Epoch 4/4\n",
      "1630/1640 [============================>.] - ETA: 0s - loss: 0.1044 - acc: 0.9902\n",
      "Epoch 00004: val_acc did not improve from 0.98649\n",
      "1640/1640 [==============================] - 23s 14ms/sample - loss: 0.1041 - acc: 0.9902 - val_loss: 0.2576 - val_acc: 0.9865\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 084 data\n",
      "1(438, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 084 trainning\n",
      "Train on 2395 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2390/2395 [============================>.] - ETA: 0s - loss: 0.2116 - acc: 0.9766\n",
      "Epoch 00001: val_acc improved from -inf to 0.97297, saving model to models\\084\\084#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2395/2395 [==============================] - 35s 15ms/sample - loss: 0.2112 - acc: 0.9766 - val_loss: 0.6626 - val_acc: 0.9730\n",
      "Epoch 2/4\n",
      "2390/2395 [============================>.] - ETA: 0s - loss: 0.0119 - acc: 0.9992\n",
      "Epoch 00002: val_acc did not improve from 0.97297\n",
      "2395/2395 [==============================] - 33s 14ms/sample - loss: 0.0183 - acc: 0.9975 - val_loss: 0.5082 - val_acc: 0.9324\n",
      "Epoch 3/4\n",
      "2390/2395 [============================>.] - ETA: 0s - loss: 0.4306 - acc: 0.9749\n",
      "Epoch 00003: val_acc did not improve from 0.97297\n",
      "2395/2395 [==============================] - 33s 14ms/sample - loss: 0.4300 - acc: 0.9749 - val_loss: 1.2510 - val_acc: 0.9459\n",
      "Epoch 4/4\n",
      "2390/2395 [============================>.] - ETA: 0s - loss: 0.0762 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 0.97297\n",
      "2395/2395 [==============================] - 33s 14ms/sample - loss: 0.0762 - acc: 1.0000 - val_loss: 0.9637 - val_acc: 0.9324\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 085 data\n",
      "1(610, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 085 trainning\n",
      "Train on 2685 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2680/2685 [============================>.] - ETA: 0s - loss: 0.2156 - acc: 0.9672\n",
      "Epoch 00001: val_acc improved from -inf to 0.98649, saving model to models\\085\\085#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2685/2685 [==============================] - 39s 15ms/sample - loss: 0.2154 - acc: 0.9672 - val_loss: 0.3734 - val_acc: 0.9865\n",
      "Epoch 2/4\n",
      "2680/2685 [============================>.] - ETA: 0s - loss: 0.0416 - acc: 0.9978\n",
      "Epoch 00002: val_acc did not improve from 0.98649\n",
      "2685/2685 [==============================] - 37s 14ms/sample - loss: 0.0416 - acc: 0.9978 - val_loss: 0.2339 - val_acc: 0.9865\n",
      "Epoch 3/4\n",
      "2680/2685 [============================>.] - ETA: 0s - loss: 0.0149 - acc: 0.9993\n",
      "Epoch 00003: val_acc did not improve from 0.98649\n",
      "2685/2685 [==============================] - 37s 14ms/sample - loss: 0.0149 - acc: 0.9993 - val_loss: 0.2571 - val_acc: 0.9730\n",
      "Epoch 4/4\n",
      "2680/2685 [============================>.] - ETA: 0s - loss: 0.0217 - acc: 0.9978\n",
      "Epoch 00004: val_acc did not improve from 0.98649\n",
      "2685/2685 [==============================] - 37s 14ms/sample - loss: 0.0217 - acc: 0.9978 - val_loss: 0.4075 - val_acc: 0.9865\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 087 data\n",
      "1(387, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 087 trainning\n",
      "Train on 2415 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2410/2415 [============================>.] - ETA: 0s - loss: 0.2854 - acc: 0.9531\n",
      "Epoch 00001: val_acc improved from -inf to 1.00000, saving model to models\\087\\087#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2415/2415 [==============================] - 36s 15ms/sample - loss: 0.2849 - acc: 0.9532 - val_loss: 0.0149 - val_acc: 1.0000\n",
      "Epoch 2/4\n",
      "2410/2415 [============================>.] - ETA: 0s - loss: 0.1291 - acc: 0.9905\n",
      "Epoch 00002: val_acc did not improve from 1.00000\n",
      "2415/2415 [==============================] - 33s 14ms/sample - loss: 0.1289 - acc: 0.9905 - val_loss: 0.0916 - val_acc: 0.9865\n",
      "Epoch 3/4\n",
      "2410/2415 [============================>.] - ETA: 0s - loss: 0.0198 - acc: 1.0000\n",
      "Epoch 00003: val_acc did not improve from 1.00000\n",
      "2415/2415 [==============================] - 33s 14ms/sample - loss: 0.0198 - acc: 1.0000 - val_loss: 0.0217 - val_acc: 0.9865\n",
      "Epoch 4/4\n",
      "2410/2415 [============================>.] - ETA: 0s - loss: 0.0043 - acc: 1.0000\n",
      "Epoch 00004: val_acc did not improve from 1.00000\n",
      "2415/2415 [==============================] - 33s 14ms/sample - loss: 0.0043 - acc: 1.0000 - val_loss: 0.0037 - val_acc: 1.0000\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    },
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Loading 088 data\n",
      "1(379, 300, 300, 3)\n",
      "2(74, 300, 300, 3)\n",
      "-->(74, 300, 300, 3)\n",
      "[[[80, 120, 300], [400]]]\n",
      "Creating their model\n",
      "Start 088 trainning\n",
      "Train on 2377 samples, validate on 74 samples\n",
      "Epoch 1/4\n",
      "2370/2377 [============================>.] - ETA: 0s - loss: 0.2517 - acc: 0.9565\n",
      "Epoch 00001: val_acc improved from -inf to 1.00000, saving model to models\\088\\088#Face_spoofing300x2_16102019_1727[80, 120, 300][400].h5\n",
      "2377/2377 [==============================] - 34s 14ms/sample - loss: 0.2510 - acc: 0.9567 - val_loss: 0.0263 - val_acc: 1.0000\n",
      "Epoch 2/4\n",
      "2370/2377 [============================>.] - ETA: 0s - loss: 0.0423 - acc: 0.9954\n",
      "Epoch 00002: val_acc did not improve from 1.00000\n",
      "2377/2377 [==============================] - 47s 20ms/sample - loss: 0.0422 - acc: 0.9954 - val_loss: 0.0082 - val_acc: 1.0000\n",
      "Epoch 3/4\n",
      "2370/2377 [============================>.] - ETA: 0s - loss: 0.0204 - acc: 0.9983\n",
      "Epoch 00003: val_acc did not improve from 1.00000\n",
      "2377/2377 [==============================] - 41s 17ms/sample - loss: 0.0204 - acc: 0.9983 - val_loss: 0.0100 - val_acc: 1.0000\n",
      "Epoch 4/4\n",
      "2370/2377 [============================>.] - ETA: 0s - loss: 0.0070 - acc: 0.9996\n",
      "Epoch 00004: val_acc did not improve from 1.00000\n",
      "2377/2377 [==============================] - 32s 14ms/sample - loss: 0.0069 - acc: 0.9996 - val_loss: 0.0024 - val_acc: 1.0000\n",
      "49569\n"
     ]
    },
    {
     "name": "stderr",
     "output_type": "stream",
     "text": [
      "Exception ignored in: <function BaseSession._Callable.__del__ at 0x000002B0F4062318>\n",
      "Traceback (most recent call last):\n",
      "  File \"E:\\Anaconda3\\envs\\face_spoofing\\lib\\site-packages\\tensorflow\\python\\client\\session.py\", line 1473, in __del__\n",
      "    self._session._session, self._handle)\n",
      "tensorflow.python.framework.errors_impl.CancelledError: (None, None, 'Session has been closed.')\n"
     ]
    }
   ],
   "source": [
    "people = os.listdir(dir_pickle)\n",
    "for person in people:\n",
    "    if person in ignore:\n",
    "        continue\n",
    "    print(f\"Loading {person} data\")\n",
    "    X, y = load_data(person)\n",
    "    ValSet = []\n",
    "    ValSet = create_validation(person)\n",
    "    print(f\"-->{ValSet[0].shape}\")\n",
    "    print(NN_formats)\n",
    "    for format_convolution, format_dense in NN_formats:\n",
    "        # Create the model structure for the person\n",
    "        print(\"Creating their model\")\n",
    "        model = create_model(person,os.path.join(dir_pickle,person),format_convolution,format_dense)\n",
    "        checkpoint = create_callbacks(person,format_convolution,format_dense)\n",
    "        #Split the serilized test to validation\n",
    "        #Train model\n",
    "        print(f\"Start {person} trainning\")\n",
    "        model.fit(X,y,batch_size=10,validation_data=ValSet,epochs=4,shuffle=False, callbacks=[checkpoint])\n",
    "        del model\n",
    "        reset_keras()\n",
    "    del X,y,ValSet"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "metadata": {},
   "outputs": [],
   "source": [
    "#kills the kernel to free-up memory on GPU, also avoiding collisions with othhers scripts \n",
    "#comment the line below, if you want to keep the variables and buffers\n",
    "os._exit(00)"
   ]
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "face_spoofing",
   "language": "python",
   "name": "face_spoofing"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.7.4"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 2
}
